### ISSUE TITLE
Charts generating excessive calls to server for historical data

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-data-financial#53]
**Problem**
We are not clear on how our Components should behave with respect to caching data. And it doesn’t sound like the Financial Component caches any data which has resulted in the biggest month-over-month cost increase for our financial server.

**How We Measure Success**
How a component caches its respective data is consistent across all components. A Component makes one remote request for data regardless if the respective data is used 100 times on a display. 

Discussion on this doc: https://docs.google.com/document/d/16McSorxwUSB23XYMdBsJLCMcQWRvOZRVnqURP6hEVIk/edit?ts=5d5565ec#heading=h.fx8vuysrv00i

**Comment by stulees** [comment]
@pcsandford @sheadarlison @alanclayton Caching data for offline play and server request reduction has been implemented in latest version of the component. Templates _bonds_ and _tsx-gainers-losers_ were used as a test/validation of the feature and have ran without issue (approx 28 user displays as well as rise vision displays). 

We won't see a significant reduction in historical financial server requests (or cost) until all financial templates are updated to use v2 of the component, which Creative are working through. In the meantime, I'm closing this issue and will monitor logs as the rest of templates get updated.
