### ISSUE TITLE
Editor allows selection of instruments that we do not get data for

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-data-financial#60]
**What should happen**

When a user searches in editor they should only see results that we have data for.

**What currently happens**

A user can search and add instruments that return as N/A or Invalid_Symbol. These are hidden in the presentation but show on their list which is confusing. Example instrument codes: .MXX, .RUT, and .FTSE.

I think it would be good to have a blacklist of elements that the selector can exclude from results. If this is based on a google sheet we can update it with codes as we find them and also edit if necessary e.g. when the market changes a listing or code changes for an instrument

**Steps to recreate**

Search for the instruments above and add them to a list in the presentation. They will not show in the table but will show in the list.

**Comment by stulees** [comment]
@pcsandford FYI, we're not going to invest effort into this at the moment, it will be tracked in our Developer Roadmap and will be addressed in the future. Thanks!
