### ISSUE TITLE
User not told when an instrument is invalid 

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-data-financial#96]
**Current User Experience**
When I add an instrument that is not valid (e.g., MXX) I am allowed to add it to my list of financial instruments without any indication that the respective data will not shown on my display. The only way I can know for certain if it is showing properly is to go physically look at my display which is time consuming. 

**Expected User Experience**
If I add an instrument that is invalid, or an existing item in my playlist has become invalid, then I should see a "Invalid instrument. Please select a different one" error on the respective playlist item, and I should not be allowed to save until I have resolved the error.

**Comment by stulees** [comment]
@alanclayton @ezequielc As per discussion [here](https://docs.google.com/document/d/10O-g0-alMmHz9PnvOTh9zEwNP0Q3r9C36_cC3p5GxHo/edit?disco=AAAAN8eLdz0), we agreed to move this to the pitch backlog. Closing the defect, thanks
